name: Publish Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1' # Weekly on Monday at 10:00

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build latest Debian version and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: 104lab/lazy-octane
          tags: "latest,8.3"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: 8.3/Dockerfile

  latest-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build latest Alpine version and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: 104lab/lazy-octane
          tags: "alpine,8.3-alpine"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: 8.3/alpine/Dockerfile

  cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["8.2", "8.1", "8.0"]
    steps:
      - uses: actions/checkout@master
      - name: Build PHP ${{ matrix.version }} CLI and publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: 104lab/lazy-octane
          tags: ${{ matrix.version }},${{ matrix.version }}-cli
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: ${{ matrix.version }}/Dockerfile

  alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["8.2", "8.1", "8.0"]
    steps:
      - uses: actions/checkout@master
      - name: Build PHP ${{ matrix.version }} Alpine and publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: 104lab/lazy-octane:${{ matrix.version }}-alpine
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: ${{ matrix.version }}/alpine/Dockerfile
